version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/snapstory
      - JWT_SECRET=your_jwt_secret_here
      - JWT_EXPIRE=30m
      - FILE_UPLOAD_PATH=./public/uploads
      - AI_SERVICE_URL=http://ai_service:5000
    volumes:
      - ./backend/public/uploads:/app/backend/public/uploads
    depends_on:
      - mongo
      - ai_service
    restart: unless-stopped

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5000
    depends_on:
      - app
    restart: unless-stopped

  ai_service:
    build:
      context: .
      dockerfile: Dockerfile.ai
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
      - MONGO_URI=mongodb://mongo:27017/snapstory
    volumes:
      - ./ai_service:/app
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo-data:
